# Config version, don't change this
config-version: 1

decay-rates:
  alcohol: 200
  toxin: 400
events:
  enabled-random-events:
    - puke
    - memory_loss
    - stumble
    - chicken
    - nausea
    - tunnel_vision
  # In minutes
  pass-out-time: 5
  messages:
    - I love you <random_player_name>, you're my best friend.
    - I could do one more.
    - Who is she?
    - Watch this!
    - I'm not drunk. You're drunk.
  custom-events:
    # Example
    memory_loss:
      steps:
        - type: pass_out
        - type: wait
          condition: join
        - type: teleport
        - type: consume
          alcohol: -30
          toxins: -15
      alcohol: 60
      toxins: 90
      probability-weight: 5
    tunnel_vision:
      steps:
        - type: potion
          effect: darkness
          duration: 20
          amplifier: 1
      alcohol: 60
      toxins: 50
      probability-weight: 20

  teleport-destinations:
    - world, 0, 80, 0
  drunken-join-deny: true
# Settings for cauldrons
cauldrons:
  # Reduce the number of particles that spawn while cauldrons brew.
  # This won't affect performance, but it will make the particles less obtrusive.
  minimal-particles: false
  # What blocks cauldrons must have below them to be able to brew.
  # Campfires must be lit and lava must be a source block.
  # If this list is empty, cauldrons will brew regardless of the block below them.
  heat-sources: [ campfire, soul_campfire, lava, fire, soul_fire, magma_block ]
sounds:
  barrel-close: minecraft:block.barrel.close
  barrel-open: minecraft:block.barrel.open
  cauldron-ingredient-add-brew: minecraft:block.pointed_dripstone.drip_water_into_cauldron
  cauldron-ingredient-add: minecraft:entity.generic.splash
  cauldron-brew-extract: minecraft:item.bottle.fill
  distillery-access: minecraft:block.vault.fall
  distillery-process: minecraft:block.brewing_stand.brew

automation-enabled: true