# Config version, don't change this
config-version: 1


events:
  enabled-random-events:
    - puke
    - memory_loss
    - stumble
    - chicken
    - drunk_message
    - nausea
  # In minutes
  pass-out-time: 5
  teleport-locations: []
  messages:
    - I love you <random_player_name>, you're my best friend.
    - I could do one more.
    - Who is she?
    - Watch this!
    - I'm not drunk. You're drunk.
  custom-events:
    # Example
    memory_loss:
      steps:
        - type: pass_out
        - type: wait
          condition: join
        - type: teleport
  teleport-destinations:
    - world, 0, 80, 0
# Settings for cauldrons
cauldrons:
  # Reduce the number of particles that spawn while cauldrons brew.
  # This won't affect performance, but it will make the particles less obtrusive.
  minimal-particles: false
  # What blocks cauldrons must have below them to be able to brew.
  # Campfires must be lit and lava must be a source block.
  # If this list is empty, cauldrons will brew regardless of the block below them.
  heat-sources: [campfire, soul_campfire, lava, fire, soul_fire, magma_block]