name: Publish Plugin

on:
  release:
    types:
      - released

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish to Hangar
        run: "./gradlew :bukkit:publishAllPublicationsToHangar"
        env:
          RELEASE_NOTES: github.event.release.body
          API_KEY: secrets.HANGAR_PUBLISH_KEY
      - name: Publish to Modrinth
        run: "./gradlew :bukkit:modrinth"
        env:
          RELEASE_NOTES: github.event.release.body
          API_KEY: secrets.MODRINTH_PUBLISH_KEY